--- #this copies from remote to remote location. remote_src points that 
- hosts: all
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Copy test file to remote system
      copy:
        src: /etc/passwd
        dest: /tmp/list_of_users
        remote_src: yes
